name: Dotnet-Core-application-CI-CD-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: 'goswamiapp001'
  PACKAGE_PATH: './publish'
  DOTNET_VERSION: '3.1.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code from Repository
      uses: actions/checkout@v2
      
    - name: Echo Message
      run: echo Hello World
