name: Dotnet-Core-application-CI-CD-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: 'goswamiapp001'
  PACKAGE_PATH: './publish'
  DOTNET_VERSION: '3.1.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code from Repository
      uses: actions/checkout@v2
      
    - name: Echo Message
      run: echo Hello World
      
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
        
#    - name: Cache NPM dependencies
#      uses: actions/cache@v1
#      with:
#        path: node_modules
#        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
#        restore-keys: |
#          ${{ runner.OS }}-npm-cache-

    - name: Build
      run: ionic cordova build android
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
   
